//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingSPAService.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bowler
    {
        public Bowler()
        {
            this.Scores = new HashSet<Score>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> Average { get; set; }
        public Nullable<int> Handicap { get; set; }
    
        public virtual ICollection<Score> Scores { get; set; }
    }
}
