//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingSPAService.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.Scores = new HashSet<Score>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int LeagueId { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual League League { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
